### ISSUE TITLE
[Feature Request]: PLAF301US / RFID Feeder | Missing Implementation for Manual Lid Opening

### ISSUE THREAD

**Issue by MrMcGyver** [jjjonesjr33/petlibro#15]
### Device model name

One RFID Smart Feeder

### Device model number

PLAF301US

### Device type

Feeder

### Feature name

Lid Feature

### Describe the feature

It would be handy to have the functionality from the app where you can manually open the lid to clean the bowl as needed

### What problem does this feature solve?

Unable to access the bowl without using the app

### Available to help with the feature development

- [X] I agree to help with testing or providing relevant information for this feature request

**Comment by jjjonesjr33** [comment]
@MrMcGyver at the moment I am missing the endpoint for us to be able to open the lid. If you're able to find the correct endpoint for me we should be good to go after that. I currently have the code pre-programmed for this feature just missing the correct API string.

**Comment by C4-Dimitri** [comment]
@jjjonesjr33 

think i got the API endpoint for the opening of the lid :)

post request to:
https://api.us.petlibro.com/device/device/doorStateChange

request data:
```

{
  "deviceSn": "AF0601314D89978A9",
  "barnDoorState": true,
  "timeout": 8000
}
```

response data:
```
{
  "code": 0,
  "msg": null,
  "data": null
}
```

so looks like we may also be able to set a length of time the door should remain open from manually triggering the opening...

very interesting...

FYI also found a new entry for: https://api.us.petlibro.com/device/data/petGrainStatus

with post request data:
`"id": "AF0601314D89978A9"`

response data:
```
{
  "code": 0,
  "msg": null,
  "data": {
    "todayFeedingQuantities": null,
    "todayFeedingQuantity": null,
    "todayFeedingTimes": null,
    "todayEatingTimes": 9,
    "eatingTime": "36'03''",
    "petGrainList": null,
    "petEatingTime": 2163
  }
}
```
might be a way for you to get data for each pet if multiple are assigned to a feeder? not that the OneRFID Feeder allows this.

let me know how you get on :)

**Comment by MrMcGyver** [comment]
Not much of a coder here. I do understand some of the logic, but have not done coding in a long time. I can work on testing on a limited basis. I do have two of these devices which may help in testing.

Thanks,

Adam R. Kniffin

**Comment by C4-Dimitri** [comment]
@jjjonesjr33 checked the timeout manually - and it seems to close roughlt 16 seconds after having been opened. so that is 500 per second, 8000 total is the default timeout.

so if we want to implement a number the user can choose for the timeout and set - we can have a number entity that ranges from say 1 second - 120 seconds. when sending to the API multiply that by 500 to get the desired result.

then we have a user definable time the lid will stay open for.

i also found the endpoint for changing the lid mode from Keep Open to Personal or vice versa.

the endpoint is:
https://api.us.petlibro.com/device/setting/updateCoverSetting

post request (`keep open`):
```
{
  "deviceSn": "AF06013AF056214A2",
  "coverOpenMode": "KEEP_OPEN",
  "coverCloseSpeed": null,
  "closeDoorTimeSec": null
}
```
post request (`personal`):
{
  "deviceSn": "AF06013AF056214A2",
  "coverOpenMode": "CUSTOM",
  "coverCloseSpeed": null,
  "closeDoorTimeSec": null
}

so that is another selection we can build in :)

**Comment by jjjonesjr33** [comment]
Completed in pull https://github.com/jjjonesjr33/petlibro/pull/23

@MrMcGyver look for a updated version to be issued here in a bit.
